### ISSUE TITLE
Support for latest stable release of Octave

### ISSUE THREAD

**Issue by mnarayan** [betatim/octave-binder#1]
I have found it challenging to run octave compatible notebooks when the octave installation is not based on the releases later than 4.0.0 found on https://launchpad.net/~octave/+archive/ubuntu/stable

The following notebooks run into errors when I tried to use them within binder with the default octave version available via apt get
https://github.com/TheEtkinLab/tutorial-prni-2017

I also haven't been able to build a base container successfully from scratch. 
Repo: https://github.com/neuroquant/MOnotebook
Docker Build: https://hub.docker.com/r/mnarayan/monotebook/

An example that illustrates how to successfully create a binder environment with Octave 4.2.2 would be really helpful.

**Comment by betatim** [comment]
How do you suggest modifying this example to use a newer version of octave?

When I launch this repository on mybinder.org and run `octave` in a terminal it prints out a version string of 4.2.x. Which sounds like it would solve your question. So I am confused about exactly what you are asking.

**Comment by jsheunis** [comment]
Hi there!

I think I have a similar challenge to the original post here. I would like to know if it is possible to install a more recent version of Octave than what Binder currently (in my case 4.2.2) installs.

Here is my repository: https://github.com/jsheunis/spm12-octave-jupyter

Here is some background information on the bug that leaded to my problem: https://github.com/spm/spm-notebooks/issues/1

I'm not an expert with Linux, `apt-get`, `apt.txt`, etc., so I just tried a few things. E.g. I tried to add `octave=4.4.0` to `apt.txt` in my Binder repo, which led to this error:

```
Step 40/54 : RUN apt-get -qq update && apt-get install --yes --no-install-recommends awscli curl ghostscript gnuplot liboctave-dev octave=4.4.0 && apt-get -qq purge && apt-get -qq clean && rm -rf /var/lib/apt/lists/*
 ---> Running in fba0e8f42438
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '4.4.0' for 'octave' was not found
Removing intermediate container fba0e8f42438
The command '/bin/sh -c apt-get -qq update && apt-get install --yes --no-install-recommends awscli curl ghostscript gnuplot liboctave-dev octave=4.4.0 && apt-get -qq purge && apt-get -qq clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

Do you have any suggestions for how to install a specific Octave version, apart from using a Dockerfile?

Best, Stephan.

**Comment by betatim** [comment]
I think the best way forward (until we upgrade the base image) is to see if using the octave package from conda-forge works for you.

The way to do that is to remove the `apt.txt` file and add `octave` to the list of packages in https://github.com/binder-examples/octave/blob/master/environment.yml

I will make a quick PR to this repository to see if that works.

**Comment by betatim** [comment]
I updated this repository. Now has octave 4.2.1.

**Comment by jsheunis** [comment]
Thanks for the feedback @betatim.

It seems like [conda-forge only has Octave version 4.2.1 available](https://anaconda.org/conda-forge/octave). Thus for my purposes using `apt.txt` (which installs v4.2.2) is still better at the moment. That is until someone either adds more recent versions of Octave to conda-forge or until the Binder base image gets updated. I know very little about either.

**Comment by gllmflndn** [comment]
Thanks for looking into this @betatim - I had the same interest than @jsheunis on having access to more recent versions of Octave on Binder and didn't know about the conda-forge option. Where can I read more about plans to upgrade the base image in Binder?
